baseURL = "/"
languageCode = "en-US"
title = "Frank Arregger-Powell"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Frank Arregger-Powell"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "frank-ap"
  LinkedIn      = "https://www.linkedin.com/in/frank-arregger-powell-62300b121/"

## Main Menu
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "cv"
  identifier = "cv"
  weight = 300
  url = "/cv/"
